### PR TITLE
net-libs/libyang: clean up, rename and a fix

### PR DESCRIPTION
**Pull request by rzalamena**
Changes:
*   Remove all old versions that don't have `LYD_PRIV_NODE`[1].
*   Remove versions with known bugs (0.16-r{1,2}).
*   Rename 0.16-r3 to its real version number `0.16.104`.
*   Fix bad assertion by disabling cache in `0.16.104`[2].

[1]: The `LYD_PRIV_NODE` first appeared in 0.16-r1 (library version number 0.16.41).
https://github.com/CESNET/libyang/issues/478

[2]: https://github.com/CESNET/libyang/issues/752

### CODE REVIEW

**Comment by f0o** [comment]
Sorry for the late answer.

Did you check that old frr builds requiring older libyang versions aren't affected by the change? I remember frr being rather picky about the version of libyang.

**Comment by rzalamena** [comment]
> Sorry for the late answer.
> 
> Did you check that old frr builds requiring older libyang versions aren't affected by the change? I remember frr being rather picky about the version of libyang.

If you want to be extremely conservative you can keep 0.16-{r1,r2}, however the older libyang version won't compile FRR (see note [1]). It is also important to note that the 0.16 series has a bug with the cache feature so it needs to be disabled to avoid [2].

Soon newer FRR version will require version 1.0 or later. I think very few FRR versions require libyang-0.16, the 7.x series can be built with 1.0.

**Comment by f0o** [comment]
Sounds about right, can you rebase this branch?

**Comment by rzalamena** [comment]
Rebased.

Also another note: our current `master` only allows FRR to build with libyang-0.16-r3 as minimum!

https://github.com/FRRouting/frr/blob/master/configure.ac#L1697

**Pull request merged**
